apiVersion: apps/v1
kind: Deployment
metadata:
  name: Productive-Horoscope-api
  labels:
    app: HoroscopeApi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HoroscopeApi
  template:
    metadata:
      labels:
        app: HoroscopeApi
    spec:
      containers:
      - name: HoroscopeApi
        image: api:4.0
        ports:
        - containerPort: 8080
        resources:
          request:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "200m"


apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels: 
    app: productive-horoscope-bd
spec:
  selector:
    app: productive-horoscope-bd
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 47300
  sessionAffinity: None
