apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: horoscope-service-ingress
spec:
  hosts: 
  - '*'
  gateways:
  - horoscope-gateway
  http:
  - match:
    - uri:
        prefix: /v1/
    rewrite:
        uri: /
    route:
    - destination:
        host: horoscopedeploy
        port:
          number: 80
  - match:
    - uri:
        prefix: /v2/
    rewrite:
        uri: /
    route:
    - destination:
        host: horoscopemirror
        port: 
          number: 80